### ISSUE TITLE
How to identify rename and removed event?

### ISSUE THREAD

**Issue by Bhushan30** [rastersize/CDEvents#28] opened 2014-02-28 11:41 UTC
CDEvent returns 67584 flags for both operation renamed and removed.
So how to identify whether which events is raised? How to get proper created, deleted, renamed, and modified events?

**Comment by rastersize** [comment] 2014-03-01 14:38
You can either check it manually by ANDing the flag you’re looking for or using the existing properties on `CDEvent` (which does this for your).

``` Objective-C
if (anEvent.flags & kFSEventStreamEventFlagItemRenamed) { [self doStuffWhenItemWasRenamed]; }
// or 
if (anEvent.isRenamed) { [self doStuffWhenItemWasRenamed]; }
```

Please notice that it is completely valid for one event to have many flags set.

CDEvents pass the exact flags back to you as Apple’s FSEvents provide. So if you think that you’re getting incorrect flags set for some event please try it out using FSEvents directly. You should then see the exact same behaviour as with CDEvents (if not please let me know). If you think that the flags are wrong please file a radar with Apple.

**Comment by Bhushan30** [comment] 2014-03-03 03:49
@rastersize  : Thanks for your feedback.. i used the above lines and tested my application so its giving me isRenamed events everytime.. for removed,modified and renamed.

Is thr any way so that i will get proper events. I need to watch 4 events created, removed. renamed and modified. Please provide me any suggestion..
For my project proper events is very important task.. So kindly please provide me your valuable feedback....

**Comment by rastersize** [comment] 2014-03-03 21:46
Indeed this can unfortunately be the situation with file level events (although I’m not able to reproduce completely on my machine at the moment). CDEvents could possibly try to interpret these events to provide a better image of what’s going on. If you want to send a pull request for such a behaviour I would gladly have a look at it. There is really nothing that can be done to improve the accuracy of the raw events though, as they are directly created by FSEvents.

I think your best option is watch the file system like you are doing. Then when you receive the events buffer them if they are not crystal clear and try to figure our what they mean. For example, if you receive two events stating that two different files have been renamed then one of them is for the old name of the file and the second for the new name. If you figure out something clever, or just which series of events represent a single atomic operation, feel free to add to this issue with that info. Or even better sending a pull request with an improvement of CDEvents.

You should definitely file a [bug/radar](http://bugreport.apple.com) with Apple about it (and then post it to [OpenRadar](openradar.me))!

As the comment for the file-level event flags goes (in CDEvents as there is almost no documentation supplied by Apple on this…):

> The entirety of the documentation on file level events in lion is 3 sentences long. Rename behavior is odd, making the combination of events and flags somewhat confusing for atomic writes. It also appears possible to get a singular event where a file has been created, modified, and removed.

Hope this was of some help at least.

**Comment by rastersize** [comment] 2014-03-10 20:27
I’ll close this issue for now but if you have further questions on the topic feel free to re-open it.

**Closed as completed by rastersize** 2014-03-10 20:27 UTC
Labels: question

**Comment by dominik0711** [comment] 2015-12-29 16:45
@rastersize  Hi. As @Bhushan30 already mentioned. CDEvent always returns isRenamed regardless of the action that a file was dropped to the watched folder. When I drop a file to the observed folder isCreated is always NO but isRenamed is always YES!
What's your suggestion to filter file changes like:
- created file to watched folder
- removed file from watched folder
- renamed file in watched folder

How to suppress notification on changes in **.DS_Store**?

This is what I have so far:

```
    _events = [[CDEvents alloc] initWithURLs:watchedURLs
                                       block:^(CDEvents *watcher, CDEvent *event) {
                                         NSString *file = event.URL.path;
                                         const std::string fileName([file UTF8String]);
                                         au::arcwork::Handler* handler = au::arcwork::Handler::GetInstance();
                                         if (event.isCreated) { // ALWAYS NO!!!
                                           handler->OnFileNotify(fileName, au::arcwork::DIR_CHANGE_TYPE::ADDED);
                                         }
                                         if (event.isRemoved) { // ALWAYS NO!!!
                                           handler->OnFileNotify(fileName, au::arcwork::DIR_CHANGE_TYPE::DELETED);
                                         }
                                         if (event.isRenamed) { // ALWAYS YES!!!
                                           ...
                                         }
                                       }
                                   onRunLoop:[NSRunLoop currentRunLoop]
                        sinceEventIdentifier:kCDEventsSinceEventNow
                        notificationLantency:CD_EVENTS_DEFAULT_NOTIFICATION_LATENCY
                     ignoreEventsFromSubDirs:CD_EVENTS_DEFAULT_IGNORE_EVENT_FROM_SUB_DIRS
                                 excludeURLs:nil
                         streamCreationFlags:creationFlags];
```

**Comment by NickEckert** [comment] 2016-08-07 01:35
@dominik0711 I'm having this exact same problem. The create flag is never returned but the rename is wether I drop a file, delete a file or rename a file in the directory I'm watching.  I was however able to trigger the create flag by manually creating a new file using touch in terminal. Were you able to make any progress since you posted this in 2015?

**Comment by DivineDominion** [comment] 2017-01-24 09:28
[Working on Swift code](https://github.com/RxSwiftCommunity/RxFileMonitor/blob/master/RxFileMonitor/FolderContentMonitor.swift) and having the same problem here. It seems FSEvent is not raising events with the same meaning we humans expect. 

As @rastersize pointed out, writing atomically results in a "write elsewhere" + move operation, resulting in `isRenamed`; writing non-atomically will actually produce `isModified`. Creating files in 3rd party apps (non-)atomically will produce the same problem. 

So when we think in terms of updating file contents, the FSEvent abstraction doesn't fit, because a rename-event that indicated overwriting the old file is, from a user's perspective, just saving changes. There's not much CDEvents can offer to solve this.
